<div class="row">
	<div class="col-xs-12">
		<div class="jumbotron">
			<h1>Bienvenue !</h1>
			<p>
				Vous êtes actuellement sur le site de la Guerre des 631 ! Ne soyez pas effrayé, ça ne fait pas mal, tant que vous évitez Hal-9000-bert et les autres dieux…
			</p>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title">Informations de connexion</h3>
			</div>
			<p class="panel-body">
				Pour vous connecter, vous devez d'abord appartenir à la secte des 631.<br >
				Entrez votre prénom, votre nom et ensuite votre mot de passe, qui est par défaut votre date de naissance sous la forme <b><span class="text-primary">JJ</span><span class="text-success">MM</span><span class="text-danger">AAAA</span></b>. Par exemple, si vous êtes né le 24 décembre 1852 (sisi Pascal &lt;3), votre mot de passe sera <b><span class="text-primary">24</span><span class="text-success">12</span><span class="text-danger">1852</span></b>.<br /><span class="text-danger">N'oubliez pas de le changer une fois connecté !</span><br />
				Oh j'oubliais, n'essayez pas de tricher, je vous vois…
			</p>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<p>
			Site entièrement refait à la demande de mes petits camarades de classe.<br />
			Pour ceux qui veulent des détail techniques bien chiants :
			<ul>
				<li>Ce site a été fait à l'aide de l'<i><a href="http://atomikframework.com">Atomik Framework</a></i>, made in France !</li>
				<li>C'est donc la troisième fois que je fais ce site : une fois en procédural, une fois en orienté objet, une fois avec Atomik (celle-ci est la meilleure)</li>
				<li>Pour le design j'utilise <i><a href="http://getbootstrap.com/">Bootstrap</a></i>, la base</li>
				<li>Ce site est hébergé chez moi sur un <i><a href="https://www.raspberrypi.org">Raspberry Pi Model A</a></i> tournant sous <i><a href="https://www.debian.org">Debian</a> (Raspbian)</i> avec <i><a href="http://nginx.org">Nginx</a></i> comme serveur web, <i><a href="http://php.net">PHP</a></i> comme CGI et <i><a href="https://www.sqlite.org/">SQLite</a></i> pour la base de données, garantissant des performances maximales</li>
				<li>Et le plus intéressant : le code source est disponible sur <a href="https://github.com/GilDev/La-Guerre-des-631">GitHub, cliquez ici pour aller voir !</a></li>
			</ul>
		</p>
	</div>
</div>