<form class="form-horizontal" method="post" action="<?php echo $this->url('modifier-mot-de-passe') ?>">
	<div class="form-group">
		<label for="pass" class="col-sm-3 control-label">Nouveau mot de passe :</label>
		<div class="col-sm-9">
			<input type="password" class="form-control" id="pass" name=pass placeholder="Nouveau mot de passe" />
		</div>
	</div>
	<div class="form-group">
		<label for="confirmPass" class="col-sm-3 control-label">Confirmation du mot de passe :</label>
		<div class="col-sm-9">
			<input type="password" class="form-control" id="confirmPass" name="confirmPass" placeholder="Confirmation du mot de passe">
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-3 col-sm-9">
			<button type="submit" class="btn btn-primary">Changer de mot de passe</button>
		</div>
	</div>
</form>